### ISSUE TITLE
How to use the toolkit to create procedural terrain generation?

### ISSUE THREAD

**Issue by edesdan** [Syomus/ProceduralToolkit#10]
Hi there, 
your toolkit looks really good. I'm actually struggling trying to find a way to procedural generate a 3d low poly terrain for a game I'm developing. I'm new to all these concepts and I would appreciate a guide/direction/tutorial from you on how to integrate the script with Unity3D. Do i need to attach the script to a 'terrain' object in Unity? I need to generate a new terrain every time the game starts a place prefabs on it. Unfortunately there is no too much documentation.  

I would appreciate any help. Thanks!

**Comment by BasmanovDaniil** [comment]
Hello and welcome!
Terrain generation example creates its mesh from scratch and has no relation to Unity's Terrain component. It consists of two scripts: generator and configurator. Generator is a static class with nothing but generation logic in it, its sole public method accepts configuration as a parameter, which is then used during generation. Configurator does several things: maps UI events to changes in config, generates random color palettes, updates skybox and runs generator. It is mostly needed for demonstration and has lots of extra code, you can write your own configurator like this:

```csharp
using ProceduralToolkit.Examples;
using UnityEngine;

public class SimpleConfigurator : MonoBehaviour
{
    public MeshFilter terrainMeshFilter;
    public LowPolyTerrainGenerator.Config config = new LowPolyTerrainGenerator.Config();

    private void Awake()
    {
        // Generate MeshDraft - helper object which allows easier modification of meshes
        var draft = LowPolyTerrainGenerator.TerrainDraft(config);
        // Move mesh pivot to the center of the terrain
        draft.Move(Vector3.left*config.terrainSize.x/2 + Vector3.back*config.terrainSize.z/2);
        // Convert MeshDraft to Mesh for MeshFilter
        var mesh = draft.ToMesh();
        // Recalculate bounds so there are no rendering artefacts
        mesh.RecalculateBounds();
        // Assign mesh to MeshFilter
        terrainMeshFilter.sharedMesh = mesh;
    }
}
```
All you need is this small class and a place for generated mesh.
![](https://monosnap.com/file/gK3Ju3JzK1XaninN8nIBLei4E6n1F5.png)
You can later extend this configurator and make something like terrain manager aout of it, add prefab placement logic and so on.

**Comment by edesdan** [comment]
Hi, thanks for your reply. Very helpful. I tried that and I got your point but now I have like 10 other questions... :sweat: 

First of all how to add a mesh collider to the terrain? Do I need to do that programmatically as well? I have tried to add it via unity editor but I cannot add the mesh because I think at that point is not there.. :confused: See here: 
<img width="542" alt="screenshot 2017-08-24 23 33 42" src="https://user-images.githubusercontent.com/5745049/29691915-37e79fb8-8925-11e7-8987-c29bde009b74.png"> 
Any suggestion to add a mesh collider?

Is it possible to use a base mesh that is not a square but instead a circle? I mean what is the best way to generate an island-like terrain mesh?

When you say 'You can later extend this configurator and make something like terrain manager out of it, add prefab placement logic and so on...' Can you explain a little bit better how you would do something like that? What's the best way for example to add prefabs like tree and so on? Do you have any recommendation for a good tutorial/website to learn all this stuffs? 

Thanks, I appreciate your time.

**Comment by BasmanovDaniil** [comment]
Once you start down the procedural path you can't turn back. 😄 Mesh collider shoud be assigned through code too, you can set it via [MeshCollider.sharedMesh](https://docs.unity3d.com/ScriptReference/MeshCollider-sharedMesh.html).

To create an island you just need to add water, you could save some triangles using circular base, but not much.
![](https://monosnap.com/file/6xdXUmbPV5sETfoQlejzt4s4wm9UXQ.png)
Actually, if you want good-looking results, you will need to change generation algorithm too. Currently it uses [Mathf.PerlinNoise](https://docs.unity3d.com/ScriptReference/Mathf.PerlinNoise.html), which is fine for example purposes, but too simple otherwise. There are many different terrain generation techniques, I would recommend starting with these tutorials: [part one](http://catlikecoding.com/unity/tutorials/noise/), [part two](http://catlikecoding.com/unity/tutorials/noise-derivatives/) and [part three](http://catlikecoding.com/unity/tutorials/simplex-noise/). They are a bit advanced, so you might want to try his [other tutorials](http://catlikecoding.com/unity/tutorials/) first. Also, you should definitely read [this famous article](http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/) from Amit Patel. Another good source of information is [Google Scholar](https://scholar.google.com/).

Regarding prefab placement, you will obviously need to use [Instantiate](https://docs.unity3d.com/ScriptReference/Object.Instantiate.html), but at which positions you should do it is highly dependent on your generation algorithm. For example, you could use a heightmap to determine areas which are not in the water and place trees randomly, then fix all collisions. Or you could generate some kind of forest map and use it instead. It also depends on your artstyle, not every style allows cheap and easy generation algorithms. All in all, I would advice you to focus on terrain generation first, solving two problems at once is detrimental in procedural generation.

**Comment by edesdan** [comment]
uhmm I see what you mean. Thanks again for all useful resources. I think I should start with something easier and leave the PG aside for the moment, I think I need to spend time understanding the basics first. :) 

I was wondering then if there is a way to use your tool and export the mesh that I create in a unity prefab or something I can use with the terrain. Do you recommend this approach? Or maybe it is just better to go and create the low poly terrain using some other tool/technique?

**Comment by BasmanovDaniil** [comment]
You can save any generated mesh using MeshFilter's context menu:
![](https://monosnap.com/file/TCfpb6sgxMATnYsQltmFDvIvmYpv81.png)
It will be saved in unity's own internal format, which means you will not be able to open it in an external editor, but any public Mesh field will accept it. It also means that Terrain component will not be able to do anything with it without extra code. If you are set to create terrain manually I can recommend [this plugin](https://www.assetstore.unity3d.com/en/#!/content/46528), with it you will still be able to use all your usual brushes and tools, but it will have the low poly look. Another good tool is [World Machine](http://www.world-machine.com/), it can give you good terrain textures relatively easy. There is also [World Creator](https://www.assetstore.unity3d.com/en/#!/content/55073), but I have not tried it myself, can't say much about it.

**Comment by edesdan** [comment]
Ah ok, thanks. Yeah I was thinking to buy the plugin you suggested. For now I simply created a low poly terrain in blender and imported it. Maybe at some point I will buy it if it will makes sense for the game I'm creating. It is a little bit expensive, but yes I think is one of the best one in the market. I'll keep following your project, I think it is very interesting and good potential to become something really useful!
