### ISSUE TITLE
Saving Generated Objects as Assets

### ISSUE THREAD

**Issue by Chapmania** [Syomus/ProceduralToolkit#8]
Hi Syomus,

Thank you for such a great Unity tool. I was hoping that you could explain how to save the objects that I have generated in ProceduralToolkit so I can use them in any scene.

Thanks in advance for your response.

Cheers - Chapmania

**Comment by BasmanovDaniil** [comment]
Hello! For meshes you can use MeshFilter extension: "MeshFilter>Save Mesh".
<img src="https://monosnap.com/file/zebe9PkC8rhf4cgtLnbYorxe5wz9XG.png">
It will save generated mesh as an .asset file, which you can use in any scene you like, but keep in mind, that you won't be able to open it in Maya or Blender, because it will be in Unity format.
<img src="https://monosnap.com/file/10M888vakgFiU7Va3zM9fd7hgQa2DM.png">
As for textures and everything else, currently there is no way to save them. You can use MeshFilterExtension code as a reference to do it yourself, if you want.
